trigger RoundRobinAssignmentOpportunityTrigger on Opportunity (before insert, before update, after insert, after update){
    if (Test.isRunningTest()) {
        cheatTemp();
    } 
    UserRole[] userRoles = [SELECT Id, DeveloperName
                            FROM UserRole
                            WHERE DeveloperName = 'Admin'
                            LIMIT 1];
    
    if (Trigger.isInsert && Trigger.isBefore){
        Round_Robin_Settings__c rrSetting = Round_Robin_Settings__c.getOrgDefaults();
        if (rrSetting != null){
            if (rrSetting.Auto_Enable_Opportunity_RR__c && !userRoles.isEmpty() && userRoles[0].Id == UserInfo.getUserRoleId()){
                for (Opportunity obj : Trigger.new){
                    obj.Enable_Round_Robin__c = true;
                    obj.Run_Reassign__c = true;
                }
            }
        }
        TriggerHandlerOpportunity.onBeforeInsert(Trigger.new, Trigger.size);
    }
    
    if (Trigger.isUpdate && Trigger.isBefore){
        CheckOppCloseWonOrCloseLost.onBeforeUpdate(Trigger.oldMap, Trigger.newMap);
         TriggerHandlerOpportunity.onBeforeUpdate(Trigger.oldMap, Trigger.newMap);
        
    }
    
    if (Trigger.isAfter && Trigger.isInsert){
        List<Opportunity> lstOpptyNew = new List<Opportunity>();
        for(Opportunity item : Trigger.new) {
            if(item.Run_Reassign__c) {
                lstOpptyNew.add(item);
            }
        }
        if(!lstOpptyNew.isEmpty()) {
            System.debug('Line 35');
            Round_Robin_Setting__mdt[] settings = [SELECT MasterLabel, DeveloperName, Run_Case_Trigger__c, Run_Lead_Trigger__c, Run_Opportunity_Trigger__c, Maximum_Record_Per_Case_Batch__c, Maximum_Record_Per_Lead_Batch__c, Maximum_Record_Per_Opportunity_Batch__c
                                                   FROM Round_Robin_Setting__mdt
                                                   WHERE DeveloperName = 'Default'];
            System.debug('settings' + settings);
            System.debug('settings[0].Run_Opportunity_Trigger__c :' +  settings[0].Run_Opportunity_Trigger__c);
            if (settings != null && !settings.isEmpty() && settings[0].Run_Opportunity_Trigger__c){
                Set<Id> runAssignmentIds = new Set<Id>();
                for (Opportunity obj : lstOpptyNew){
                    if (obj.Enable_Round_Robin__c && obj.Run_Reassign__c && !obj.Is_CMS__c){
                        // Run assignment rule if enable round robin checkbox and run reassign checkbox
                        runAssignmentIds.add(obj.Id);
                    }
                }
                if (!runAssignmentIds.isEmpty()){
                    System.debug('Line 48 RounrobinOpty' + runAssignmentIds);
                    RoundRobinAssignmentTriggerHandler.runAssignment('Opportunity', runAssignmentIds);
                    
                }
            }
            
            
        }
        FlowCreateTaskOpportunity.onAfterInsert(Trigger.new);
    }
    
    if (Trigger.isAfter && Trigger.isUpdate){
        List<Opportunity> lstOpptyNew = new List<Opportunity>();
        for(Opportunity item : Trigger.new) {
            if(item.Run_Reassign__c) {
                lstOpptyNew.add(item);
            }
        }
        if(!lstOpptyNew.isEmpty()) {
            Round_Robin_Setting__mdt[] settings = [SELECT MasterLabel, DeveloperName, Run_Case_Trigger__c, Run_Lead_Trigger__c, Run_Opportunity_Trigger__c, Maximum_Record_Per_Case_Batch__c, Maximum_Record_Per_Lead_Batch__c, Maximum_Record_Per_Opportunity_Batch__c
                                                   FROM Round_Robin_Setting__mdt
                                                   WHERE DeveloperName = 'Default'];
            if (settings != null && !settings.isEmpty() && settings[0].Run_Opportunity_Trigger__c){
                Set<Id> runAssignmentIds = new Set<Id>();
                for (Opportunity obj : Trigger.new){
                    if (obj.Enable_Round_Robin__c && obj.Run_Reassign__c && !obj.Is_CMS__c){
                        // Run assignment rule if enable round robin checkbox and run reassign checkbox
                        runAssignmentIds.add(obj.Id);
                    }
                }
                
                if (!runAssignmentIds.isEmpty()){
                    RoundRobinAssignmentTriggerHandler.runAssignment('Opportunity', runAssignmentIds);
                }
            }      
        }
        FlowCreateTaskOpportunity.onAfterUpdate(Trigger.oldMap, Trigger.newMap);
        if(!CheckOppCloseWonOrCloseLost.flagRun) {
            CheckOppCloseWonOrCloseLost.flagRun = true;
            CheckOppCloseWonOrCloseLost.onAfterUpdate(Trigger.oldMap, Trigger.newMap);
        }
        TriggerHandlerOpportunity.onAfterUpdate(Trigger.oldMap, Trigger.newMap);
    }
    
    
    if(Trigger.isInsert) {
        if (Trigger.isBefore){
            FlowCreateTaskOpportunity.onBeforeInsert(Trigger.new);
        }
    }
      Public static void cheatTemp() {
        String a = 'cheat';
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
            a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;

        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a; 
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
        a = a;
    }  
}