@isTest
public class RecordTypeHelperTest {
	@isTest
    static void test()
    {
        String test = '';
        test = RecordTypeHelper.ACCOUNT_BRANCH;
        test = RecordTypeHelper.ACCOUNT_CUSTOMER;
        test = RecordTypeHelper.ACCOUNT_DODL;
        test = RecordTypeHelper.ACCOUNT_SUPPLIER;
        test = RecordTypeHelper.CAMPAIGN_RECALL;
        test = RecordTypeHelper.CAMPAIGNRECALL;
        test = RecordTypeHelper.CONDITION;
        test = RecordTypeHelper.CONTACT;
        test = RecordTypeHelper.CONTACT_EMPLOYEE;
        test = RecordTypeHelper.COUPON;
        test = RecordTypeHelper.CRMOWNERSHIP;
        test = RecordTypeHelper.DMSOWNERSHIP;
        test = RecordTypeHelper.FOLLOW_FAIL_ACCOUNT;
        test = RecordTypeHelper.FOLLOW_FAIL_LEAD;
        test = RecordTypeHelper.FOLLOW_LEAD;
        test = RecordTypeHelper.FOLLOWFAIL_AFTERSALE;
        test = RecordTypeHelper.OPPORTUNITY_BIKE;
        test = RecordTypeHelper.OPPORTUNITY_PCA;
        test = RecordTypeHelper.ORDER_ACCOUNT_BIKE;
        test = RecordTypeHelper.ORDER_ACCOUNT_PCA;
        test = RecordTypeHelper.ORDER_ACCOUNT_SERVICE;
        test = RecordTypeHelper.ORDER_BIKE;
        test = RecordTypeHelper.ORDER_APPRAISAL;
        test = RecordTypeHelper.ORDER_FREE_COUPON;
        test = RecordTypeHelper.ORDER_FREE_SERVICE;
        test = RecordTypeHelper.ORDER_INSTALLATION;
		test = RecordTypeHelper.ORDER_INTERNAL_SERVICE;
        test = RecordTypeHelper.ORDER_PCA;
        test = RecordTypeHelper.ORDER_PROFOMAR_ORDER;       
        test = RecordTypeHelper.ORDER_QUICK_SERVICE;
        test = RecordTypeHelper.ORDER_RECALL;
        test = RecordTypeHelper.ORDER_SERVICE_ORDER; 
        test = RecordTypeHelper.ORDER_SERVICE_PACKAGE;
        test = RecordTypeHelper.ORDER_WARRANTY;
        test = RecordTypeHelper.PART;  
        test = RecordTypeHelper.PRODUCT_MODEL;  
        test = RecordTypeHelper.PRODUCT_PCA; 
        test = RecordTypeHelper.PRODUCT_SERVICE_PACKAGE; 
        test = RecordTypeHelper.PROMOTIONDEFAULT; 
        test = RecordTypeHelper.PROMOTIONITEMDISCOUNT; 
        test = RecordTypeHelper.PROMOTIONITEMDISCOUNTAM; 
        test = RecordTypeHelper.PROMOTIONVOUCHER; 
        test = RecordTypeHelper.QUOTE_SALES;
        test = RecordTypeHelper.QUOTE_SALES_BIKE;
        test = RecordTypeHelper.QUOTE_TRADE_IN;
    }
}