public class RemoveVietnameseTone {
    private static final String[] SOURCE_CHARACTERS = new String[]{'Tỉnh','Thành phố','À', 'Á', 'Â', 'Ã', 'È', 'É',
    'Ê', 'Ì', 'Í', 'Ò', 'Ó', 'Ô', 'Õ', 'Ù', 'Ú', 'Ý', 'à', 'á', 'â',
    'ã', 'è', 'é', 'ê', 'ì', 'í', 'ò', 'ó', 'ô', 'õ', 'ù', 'ú', 'ý',
    'Ă', 'ă', 'Đ', 'đ', 'Ĩ', 'ĩ', 'Ũ', 'ũ', 'Ơ', 'ơ', 'Ư', 'ư', 'Ạ',
    'ạ', 'Ả', 'ả', 'Ấ', 'ấ', 'Ầ', 'ầ', 'Ẩ', 'ẩ', 'Ẫ', 'ẫ', 'Ậ', 'ậ',
    'Ắ', 'ắ', 'Ằ', 'ằ', 'Ẳ', 'ẳ', 'Ẵ', 'ẵ', 'Ặ', 'ặ', 'Ẹ', 'ẹ', 'Ẻ',
    'ẻ', 'Ẽ', 'ẽ', 'Ế', 'ế', 'Ề', 'ề', 'Ể', 'ể', 'Ễ', 'ễ', 'Ệ', 'ệ',
    'Ỉ', 'ỉ', 'Ị', 'ị', 'Ọ', 'ọ', 'Ỏ', 'ỏ', 'Ố', 'ố', 'Ồ', 'ồ', 'Ổ',
    'ổ', 'Ỗ', 'ỗ', 'Ộ', 'ộ', 'Ớ', 'ớ', 'Ờ', 'ờ', 'Ở', 'ở', 'Ỡ', 'ỡ',
    'Ợ', 'ợ', 'Ụ', 'ụ', 'Ủ', 'ủ', 'Ứ', 'ứ', 'Ừ', 'ừ', 'Ử', 'ử', 'Ữ',
    'ữ', 'Ự', 'ự','Ỳ','ỳ'};

private static final String[] DESTINATION_CHARACTERS =  new String[]{ 'Province','City','A', 'A', 'A', 'A', 'E',
    'E', 'E', 'I', 'I', 'O', 'O', 'O', 'O', 'U', 'U', 'Y', 'a', 'a',
    'a', 'a', 'e', 'e', 'e', 'i', 'i', 'o', 'o', 'o', 'o', 'u', 'u',
    'y', 'A', 'a', 'D', 'd', 'I', 'i', 'U', 'u', 'O', 'o', 'U', 'u',
    'A', 'a', 'A', 'a', 'A', 'a', 'A', 'a', 'A', 'a', 'A', 'a', 'A',
    'a', 'A', 'a', 'A', 'a', 'A', 'a', 'A', 'a', 'A', 'a', 'E', 'e',
    'E', 'e', 'E', 'e', 'E', 'e', 'E', 'e', 'E', 'e', 'E', 'e', 'E',
    'e', 'I', 'i', 'I', 'i', 'O', 'o', 'O', 'o', 'O', 'o', 'O', 'o',
    'O', 'o', 'O', 'o', 'O', 'o', 'O', 'o', 'O', 'o', 'O', 'o', 'O',
    'o', 'O', 'o', 'U', 'u', 'U', 'u', 'U', 'u', 'U', 'u', 'U', 'u',
    'U', 'u', 'U', 'u','Y','y'};

    public static String RemoveTone(String str){
        String result =str;      
        for (Integer j=2; j <SOURCE_CHARACTERS.size();j++){
            result = result.replace(SOURCE_CHARACTERS[j], DESTINATION_CHARACTERS[j]);
        }  
        return result;
    }
    public static String RemoveToneProvince(String str){
        String result =str;      
        for (Integer j=0; j <SOURCE_CHARACTERS.size();j++){
            result = result.replace(SOURCE_CHARACTERS[j], DESTINATION_CHARACTERS[j]);
        }  
        if (result.substring(0, 8) == 'Province'){
           result = changeStringProvinceEnglish(result,'Province');
        }
        if (result.substring(0, 4) == 'City'){
           result = changeStringProvinceEnglish(result,'City');
        }
        return result.trim();
    }

    public static String changeStringProvinceEnglish(String strToChange,String changeTo){
        String changed = strToChange.remove(changeTo);
        return changed +' ' + changeTo;
    }
   
      
}